engines:
  eslint:
    enabled: true
  jshint:
    enabled: true
  duplication:
    enabled: true
    exclude_paths:
      - src/*.test.*
      - lib/*.test.*
  metrics:
    enabled: true
  coverage:
    enabled: true
    exclude_paths:
      - src/*.test.*
      - lib/*.test.*
